// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeImZ-gZHcL2QUwjXUiHI7jirmZXx5pYY',
    appId: '1:631304765359:android:3ac66787e990de375f395a',
    messagingSenderId: '631304765359',
    projectId: 'biz-global-001',
    storageBucket: 'biz-global-001.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeImZ-gZHcL2QUwjXUiHI7jirmZXx5pYY',
    appId: '1:631304765359:web:3ac66787e990de375f395a',
    messagingSenderId: '631304765359',
    projectId: 'biz-global-001',
    authDomain: 'biz-global-001.firebaseapp.com',
    storageBucket: 'biz-global-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeImZ-gZHcL2QUwjXUiHI7jirmZXx5pYY',
    appId: '1:631304765359:ios:3ac66787e990de375f395a',
    messagingSenderId: '631304765359',
    projectId: 'biz-global-001',
    storageBucket: 'biz-global-001.appspot.com',
    iosBundleId: 'com.bizglobal.app',
  );
}
